const arrBulletinList = [
      [
        {title: '게시판1', content: '아 어려워1'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
      ],
      [
        {title: '게시판2', content: '아 어려워1'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
      ],
      [
        {title: '게시판3', content: '아 어려워1'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
      ],
      [
        {title: '게시판4', content: '아 어려워1'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판6', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판7', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판8', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판9', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판10', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판11', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판12', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판1', content: '아 어려워1'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
      ],
      [
        {title: '게시판2', content: '아 어려워1'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
      ],
      [
        {title: '게시판3', content: '아 어려워1'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
      ],
      [
        {title: '게시판4', content: '아 어려워1'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판6', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판7', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판8', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판9', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판10', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판11', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판12', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
  ]
  
import axios from 'axios'  
  
const AXIOS = axios.create({
  baseURL: `/api`,
});

export default {
	api_getArrBulletinList(nCnt) {
    console.log('테스트');
    console.log(nCnt);

    AXIOS({
      url: '/getBulList', 
      method: 'post',
      params :{
        cnt : nCnt
      } 
    })
    .then(function (response) {
      // handle success
      console.log(response);

      let data = response.data;
      
      return [data.list, data.cnt];

      // console.log(data);      
    })
    .catch(function (error) {
      // handle error
      console.log(error);
    })
    
    //setTimeout(() => data(arrBulletinList), 400)
	}
}