const arrBulletinList = [
      [
        {title: '게시판1', content: '아 어려워1'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
      ],
      [
        {title: '게시판2', content: '아 어려워1'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
      ],
      [
        {title: '게시판3', content: '아 어려워1'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
      ],
      [
        {title: '게시판4', content: '아 어려워1'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판6', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판7', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판8', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판9', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판10', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판11', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판12', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판1', content: '아 어려워1'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
        {title: '게시판1', content: '아 어려워23'},
      ],
      [
        {title: '게시판2', content: '아 어려워1'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
        {title: '게시판2', content: '아 어려워23'},
      ],
      [
        {title: '게시판3', content: '아 어려워1'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
        {title: '게시판3', content: '아 어려워23'},
      ],
      [
        {title: '게시판4', content: '아 어려워1'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
        {title: '게시판4', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판6', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판7', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판8', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판9', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판10', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판11', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판12', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
      [
        {title: '게시판5', content: '아 어려워1'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
        {title: '게시판5', content: '아 어려워23'},
      ],
	]
  
const axios = require('axios');  

export default {
	getArrBulletinList: function(data) {
    console.log('테스트');

    axios.get('/api/getBulList')
    .then(function (response) {
      // handle success
      console.log(response);
      let arr = response.data;
      let arrList = [];
      arrList.push(arr);
      data(arrList)
    })
    .catch(function (error) {
      // handle error
      console.log(error);
    })
    
    //setTimeout(() => data(arrBulletinList), 400)
	}
}